// GENERATED by `cargo run -p xtask -- bindings` — 禁止手工修改本文件。
// 来源：crates/shared/src/dto.rs（Rust 单一来源；CI 以 --check 再生成 diff 校验）。

export interface AiConversationDto {
  createdAt: number
  id: number
  messages: AiMessageDto[]
  questId: number | null
  title: string
}

export interface AiMessageDto {
  content: string
  createdAt: number
  id: number
  role: string
}

export interface AiProfileDto {
  baseUrl: string | null
  channel: string
  cliKind: 'claude' | 'codex' | 'opencode' | null
  cliVersion: string | null
  commandPath: string | null
  configFingerprint: string | null
  extraJson: string | null
  hasSecret: boolean
  id: number
  isActive: boolean
  model: string
  name: string
}

export interface AiProfileInput {
  apiKey: string | null
  baseUrl: string | null
  channel: string
  cliKind: 'claude' | 'codex' | 'opencode' | null
  commandPath: string | null
  extraJson: string | null
  id: number | null
  model: string
  name: string
}

export interface AiStreamEvent {
  cached: boolean
  error: AppError | null
  kind: string
  requestId: number
  text: string | null
}

export interface AiTestResult {
  message: string
  ok: boolean
  rawOutput: string | null
}

export interface AppError {
  detail: string | null
  kind: string
  message: string
}

export interface AppInitInfo {
  aiAvailability: string
  dictAvailable: boolean
  indexReady: boolean
  pendingRestore: boolean
  schemaVersion: number
  termsAccepted: boolean
}

export interface BackupSummary {
  counts: TableCount[]
  createdAt: number
  path: string
  schemaVersion: number
}

export interface BatchSyncReport {
  cancelled: boolean
  failed: SyncFailure[]
  handle: number
  succeeded: number
  total: number
}

export interface BatchSyncStatus {
  progress: SyncProgress
  report: BatchSyncReport | null
}

export interface BlockBrief {
  initDialogId: string
  stepId: string
  subQuestId: string
  treeNo: number
  treeOrder: number
}

export interface BlockKey {
  stepId: string
  subQuestId: string
  treeNo: number
}

export interface CandidateForm {
  form: string
  formKind: string
  sourceNote: string | null
}

export interface ConflictBrief {
  detailJson: string
  dialogId: string
  id: number
  kind: string
  stepId: string
  subQuestId: string
  treeNo: number
}

export interface DictEntryDto {
  common: boolean
  glosses: GlossDto[]
  headword: string
  matchedForm: string
  matchedFormKind: string
  matchedSourceNote: string | null
  pos: string[]
  readingKana: string | null
  source: string
  termTexts: LangText[] | null
}

export interface DictSearchResult {
  dictAvailable: boolean
  entries: DictEntryDto[]
}

export interface DlgLoc {
  dialogId: string
  questId: number
  stepId: string
  subQuestId: string
  treeNo: number
}

export interface FetchJobStatus {
  completed: number
  error: string | null
  handle: number
  phase: string
  questId: number
  state: string
  total: number
}

export interface GlossDto {
  lang: string
  texts: string[]
}

export interface GraphSnapshot {
  alignStatus: string
  blockOrder: BlockKey[]
  conflicts: ConflictBrief[]
  followLang: string
  nodes: NodeDto[]
  questId: number
  rows: RowDto[]
  subQuestId: string
  subs: SubQuestBrief[]
  trees: BlockBrief[]
}

export interface LangText {
  lang: string
  text: string
}

export interface NodeDto {
  branchDepth: number
  danglingNext: string | null
  dialogId: string
  displaySeq: number
  isJoin: boolean
  kind: NodeKind
  status: NodeAlignStatus
  stepId: string
  subQuestId: string
  treeNo: number
}

export interface NoteDto {
  aiGeneratedJson: string | null
  analysisSnapshotJson: string | null
  contextNext: string | null
  contextRole: string | null
  contextText: string | null
  createdAt: number
  id: number
  kind: string
  optRef: OptRef
  origin: string
  provenanceStale: boolean
  staleReason: string | null
  tags: string[]
  termBase: string | null
  termReading: string | null
  termText: string | null
  updatedAt: number
  userNote: string | null
}

export interface NotesByTask {
  groups: TaskNotesGroup[]
}

export interface OpenQuestResult {
  cached: boolean
  job: FetchJobStatus | null
  snapshot: GraphSnapshot | null
}

export interface OptRef {
  dialogId: string
  optIndex: number
  questId: number
  stepId: string
  subQuestId: string
  treeNo: number
}

export interface OverrideHitDto {
  reading: string
  scope: string
}

export interface QuestOverview {
  blockOrder: BlockKey[]
  conflicts: ConflictBrief[]
  subs: SubQuestBrief[]
  summary: QuestSummary
  trees: BlockBrief[]
}

export interface QuestSummary {
  alignStatus: string | null
  chapterCount: number
  chapterNum: string | null
  hasCachedBody: boolean
  questId: number
  questType: string | null
  route: string | null
  titles: LangText[]
}

export interface ReadingProgressDto {
  dialogId: string
  optIndex: number
  pathStackJson: string
  questId: number
  stepId: string
  subQuestId: string
  treeNo: number
  updatedAt: number
}

export interface RefreshOutcome {
  alignStatus: string | null
  error: string | null
  outcome: string
  questId: number
}

export interface RestoreCheck {
  compatible: boolean
  counts: TableCount[]
  fileSize: number
  integrityOk: boolean
  path: string
  schemaVersion: number
  sha256: string
}

export interface RowDto {
  lang: string
  nextDialogId: string | null
  opt: OptRef
  role: string | null
  text: string | null
}

export interface SaveNoteInput {
  analysisSnapshotJson: string | null
  contextIsChoice: boolean
  contextNext: string | null
  contextRole: string | null
  contextText: string | null
  kind: string
  optRef: OptRef
  tags: string[]
  termBase: string | null
  termReading: string | null
  termText: string | null
  userNote: string | null
}

export interface SubQuestBrief {
  descs: LangText[]
  hasProgress: boolean
  sort: number
  subQuestId: string
  titles: LangText[]
}

export interface SyncFailure {
  questId: number
  reason: string
  title: string | null
}

export interface SyncProgress {
  currentJob: FetchJobStatus | null
  currentQuestTitle: string | null
  done: number
  failedCount: number
  handle: number
  total: number
}

export interface TableCount {
  count: number
  label: string
}

export interface TaskNotesGroup {
  notes: NoteDto[]
  questId: number
  questTitle: string | null
}

export interface UpdateReport {
  changed: QuestSummary[]
  newQuests: QuestSummary[]
  unknownBody: QuestSummary[]
}

// 字面量联合（Rust 侧常量清单生成）
export type NodeKind = 'talk' | 'choice' | 'narration'
export type NodeAlignStatus = 'ok' | 'missing_side' | 'conflict' | 'dangling'
export type FetchJobState = 'queued' | 'fetching' | 'done' | 'failed' | 'cancelled'
export type FormKind = 'surface' | 'base' | 'reading'
export type DictSource = 'term' | 'zhwiktionary' | 'jmdict' | 'jmnedict'
export type OverrideScope = 'dialog' | 'quest' | 'global'
export type AiAvailability = 'unconfigured' | 'configured_available' | 'configured_unavailable'
export type AiChannel = 'cli' | 'http'
export type CliKind = 'claude' | 'codex' | 'opencode'
export type AppErrorKind = 'network' | 'data_source' | 'data_integrity' | 'resource_missing' | 'isolation' | 'ai_channel' | 'cancelled' | 'invalid_param' | 'internal'

